get 성공 테스트 완료

diff --git a/git-credential-helper-kwalletcli b/git-credential-helper-kwalletcli
--- a/git-credential-helper-kwalletcli
+++ b/git-credential-helper-kwalletcli
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
+#set -eux -o pipefail
+#shopt -s failglob
+
 # Options
 #  --wallet=[walletname default kdewallet] 
 # Refs
@@ -24,8 +27,10 @@ case $1 in
         storedPassword=`kwalletcli -f $FOLDER_NAME -e "$GIT_PROTOCOL://$GIT_USERNAME@$GIT_HOST"`
         if [ ! -z "$storedPassword" ]
         then
-            echo "username=$GIT_USERNAME"
-            echo "passowrd=$storedPassword"
+            echo "protocol=${GIT_PROTOCOL}"
+            echo "host=${GIT_HOST}"
+            echo "username=${GIT_USERNAME}"
+            echo "password=${storedPassword}"
         fi
         ;;
     store)
